### PR TITLE
Use demo for tests. Fix docs

### PR DESCRIPTION
**Pull request by IanButterworth**
This package doesn't work for me on MacOS Silicon due to https://github.com/Gnimuc/CImGui.jl/issues/74 and I was surprised to see there weren't any tests.

This
- Reuses the demo as an easy test to run
- Fixes tests on linux x64 via xvfb
- Updates to handle Documenter v1.0.0 which was being picked up with breakages due to a lack of compat entry for it.
- Fixes broken links in the docs
- Updates one part of an example that was outdated (rest of example not checked)

### CODE REVIEW

**Comment by Gnimuc** [comment]
looks like CI is not happy. better to exclude the test in CI.

**Comment by IanButterworth** [comment]
I could try getting it working with xvfb?

**Comment by IanButterworth** [comment]
@Gnimuc I've been trying to figure out what the broken link in the docs to `IsDataType` should be. It's not even in the commit where that doc was added https://github.com/Gnimuc/CImGui.jl/commit/5847ae98de3ef8def7598fe979eafd01b5c57937

**Comment by IanButterworth** [comment]
Should be good to review now @Gnimuc  

Just see https://github.com/Gnimuc/CImGui.jl/pull/94#issuecomment-1732658140

**Comment by Gnimuc** [comment]
> @Gnimuc I've been trying to figure out what the broken link in the docs to `IsDataType` should be. It's not even in the commit where that doc was added [5847ae9](https://github.com/Gnimuc/CImGui.jl/commit/5847ae98de3ef8def7598fe979eafd01b5c57937)
> 
> I see `ImGuiPayload_IsDataType` in lbcimgui. Perhaps there's a missing wrapper function for that?

Yes. Some C++ methods are not wrapped.

**Pull request merged**
