### PR TITLE
Prepare for v4

### PR DESCRIPTION
**Pull request by JamesWrigley**
Depends on https://github.com/JuliaPackaging/Yggdrasil/pull/9810.

### CODE REVIEW

**Comment by Gnimuc** [comment]
I want to move this package to the JuliaIMGUI org before v4.

**Comment by Gnimuc** [comment]
Do you know whether we need to update Julia registry metadata or nor?

**Comment by JamesWrigley** [comment]
Sure, fine with me :) Yeah we'll need to update the registry like e.g. https://github.com/JuliaRegistries/General/pull/118235. If you transfer the repo to the organization I can make the registry PR?

**Comment by Gnimuc** [comment]
OK. After this PR is merged. I'll transfer the repo to the org.

**Comment by JamesWrigley** [comment]
Alrighty, finally done :sleepy: @Gnimuc I'll wait for you to transfer the repo, then I'll make a PR to update the registry, and then release v4.

**Comment by Gnimuc** [comment]
done!

**Comment by JamesWrigley** [comment]
Thanks :heart:

**Pull request merged**
